backend:
  name: github
  repo: enoragon/Enoch-Bradshaw-Portfolio-CMS
media_folder: "static/assets"
public_folder: "/assets"
collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: image, label: Image, widget: image }
      - { name: title, label: Title }
      - { name: text, label: Text, widget: markdown }
  - name: art
    label: Art
    folder: content/art
    create: true
    fields:
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }